leftnav:
- identifier: d7af6f0e-52b9-b87c-84b6-70fc3afc2552
  name: 2020 Videos
  pageRef: /video_galleries/videos
  weight: 10
- identifier: 94102c10-a61e-495b-b2db-3220be47cf4a
  name: 2021 Video
  pageRef: /pages/2021-video
  weight: 20
- identifier: bd03df2d-5d8b-481b-8bb8-5ebf51713493
  name: 2023 Video
  pageRef: /pages/2023-video
  weight: 30
- identifier: d88ee1e7-0af9-160e-5a0d-6210e3f7aae6
  name: Related Resources
  pageRef: /pages/relatedresources
  weight: 40
